name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code (Step 1)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker login (Step 2)
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build Docker Image (Step 3)
      run: docker build -t lypthusdev/docker-graphql:0.0.2 .
        
    - name: Push Docker Image (Step 4)
      run: docker push lypthusdev/docker-graphql:0.0.2
      
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
